spring:
  application:
    name: job-data-api
  datasource:
    driver-class-name: org.h2.Driver
    password: admin
    url: jdbc:h2:mem:salarydb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog-master.yml

server:
  tomcat:
    relaxed-query-chars: '|,{,},[,],^'

